/**
 * Monitoring & Observability
 *
 * Wraps Sentry for error tracking and custom events.
 * Sentry is initialized via sentry.client.config.ts / sentry.server.config.ts
 * (generated by `npx @sentry/wizard@latest -i nextjs`).
 *
 * Until Sentry is installed, this module is a safe no-op shim.
 *
 * To enable:
 *   1. npm install @sentry/nextjs
 *   2. npx @sentry/wizard@latest -i nextjs
 *   3. Add SENTRY_DSN to Vercel env vars
 */

// Sentry loaded lazily via require() — no type import needed at build time
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let Sentry: any = null

try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  Sentry = eval("require")('@sentry/nextjs')
} catch {
  // Sentry not installed yet — all calls are no-ops
}

export function captureError(err: unknown, context?: Record<string, unknown>) {
  if (!Sentry) {
    console.error('[monitoring] captureError (Sentry not installed):', err, context)
    return
  }
  Sentry.withScope((scope: any) => {
    if (context) scope.setExtras(context)
    Sentry.captureException(err)
  })
}

export function trackEvent(name: string, data?: Record<string, unknown>) {
  if (!Sentry) {
    if (process.env.NODE_ENV === 'development') {
      console.log(`[monitoring] Event: ${name}`, data)
    }
    return
  }
  Sentry.addBreadcrumb({ category: 'event', message: name, data, level: 'info' })
}

/**
 * Track AI generation cost.
 * Claude Sonnet input: ~$3/M tokens, output: ~$15/M tokens
 */
export function trackGenerationCost(opts: {
  userId: string
  planTier: string
  mlsId: string
  durationMs: number
  estimatedInputTokens?: number
  estimatedOutputTokens?: number
}) {
  const inputCost = ((opts.estimatedInputTokens ?? 1500) / 1_000_000) * 3
  const outputCost = ((opts.estimatedOutputTokens ?? 2500) / 1_000_000) * 15
  const totalCost = inputCost + outputCost

  trackEvent('campaign.generated', {
    userId: opts.userId,
    planTier: opts.planTier,
    mlsId: opts.mlsId,
    durationMs: opts.durationMs,
    estimatedCostUsd: parseFloat(totalCost.toFixed(4)),
  })

  if (totalCost > 0.10) {
    // Alert if a single generation costs more than $0.10
    captureError(new Error(`High generation cost: $${totalCost.toFixed(4)}`), opts)
  }
}

export function trackPlanUpgrade(opts: { userId: string; fromPlan: string; toPlan: string }) {
  trackEvent('plan.upgraded', opts)
}
