-- Migration 0005: Rename costar_* identifiers to provider-neutral names
--
-- Renames:
--   TABLE  costar_reports           → site_reports
--   ENUM   costar_source            → report_source
--   COLUMN property_grades.costar_report_id → site_report_id
--   INDEX  costar_org_id_idx        → site_report_org_id_idx
--   INDEX  costar_user_id_idx       → site_report_user_id_idx
--   INDEX  grade_costar_report_idx  → grade_site_report_idx
--
-- Safety: entire migration runs inside a single transaction.
-- If any step fails, Postgres rolls back the whole thing — no partial state.
-- The app deploy MUST happen after this migration completes (not before).
--
-- Zero data loss: RENAME operations in Postgres are metadata-only.
-- No rows are touched, no data is copied, no table locks beyond the rename itself.

BEGIN;

-- ── 1. Rename the table ────────────────────────────────────────
ALTER TABLE IF EXISTS "costar_reports" RENAME TO "site_reports";

-- ── 2. Rename the source enum ──────────────────────────────────
-- Postgres 13+ supports ALTER TYPE ... RENAME directly.
-- The enum VALUES (manual_upload, api_push, email_forward) are unchanged.
ALTER TYPE IF EXISTS "costar_source" RENAME TO "report_source";

-- ── 3. Rename the FK column on property_grades ─────────────────
ALTER TABLE "property_grades"
  RENAME COLUMN "costar_report_id" TO "site_report_id";

-- ── 4. Rename indexes on site_reports ──────────────────────────
ALTER INDEX IF EXISTS "costar_org_id_idx"  RENAME TO "site_report_org_id_idx";
ALTER INDEX IF EXISTS "costar_user_id_idx" RENAME TO "site_report_user_id_idx";

-- ── 5. Rename index on property_grades ─────────────────────────
ALTER INDEX IF EXISTS "grade_costar_report_idx" RENAME TO "grade_site_report_idx";

-- ── 6. Rename the FK constraint (name auto-generated by Postgres) ──
-- Find and rename the FK from property_grades → site_reports.
-- We use a DO block because the constraint name is auto-generated and
-- may vary across environments — this finds it dynamically.
DO $$
DECLARE
  v_constraint TEXT;
BEGIN
  SELECT conname INTO v_constraint
  FROM pg_constraint
  WHERE conrelid = 'property_grades'::regclass
    AND confrelid = 'site_reports'::regclass
    AND contype = 'f'
  LIMIT 1;

  IF v_constraint IS NOT NULL AND v_constraint != 'property_grades_site_report_id_fkey' THEN
    EXECUTE format(
      'ALTER TABLE property_grades RENAME CONSTRAINT %I TO property_grades_site_report_id_fkey',
      v_constraint
    );
  END IF;
END $$;

COMMIT;
