import Link from 'next/link'
import { House } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--cream)]">
      <nav className="fixed top-0 inset-x-0 z-50 glass border-b border-amber-100/60">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-8 h-8 bg-slate-900 rounded-lg flex items-center justify-center">
              <House className="w-4 h-4 text-amber-400" />
            </div>
            <span className="font-display font-semibold text-slate-900 text-lg">ListOps</span>
          </Link>
        </div>
      </nav>
      <div className="pt-28 pb-24 px-4 sm:px-6 lg:px-8 max-w-3xl mx-auto">
        <h1 className="font-display text-4xl font-semibold text-slate-900 mb-3">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
        <div className="space-y-8 text-sm leading-relaxed text-slate-700">
          {[
            { title: '1. Acceptance', body: 'By creating an account or using ListOps, you agree to these Terms. If you do not agree, do not use the service.' },
            { title: '2. Service Description', body: 'ListOps provides AI-powered marketing campaign generation for real estate listings via MLS data integration. The service is provided "as-is" and output is AI-generated — you are responsible for reviewing content before publishing.' },
            { title: '3. Account & Billing', body: 'You must provide accurate information when creating an account. Free accounts include 3 campaigns per month. Paid subscriptions are billed monthly or annually as selected. Cancellations take effect at end of billing period — no refunds for partial periods.' },
            { title: '4. Acceptable Use', body: 'You may not use ListOps to generate misleading or fraudulent real estate listings, violate MLS rules or real estate licensing laws, resell or white-label the service without a Brokerage or Enterprise plan, or attempt to reverse-engineer or scrape the platform.' },
            { title: '5. AI-Generated Content', body: 'Content generated by Claude AI is provided as a starting point. You are solely responsible for reviewing, editing, and ensuring accuracy of all published marketing content. ListOps is not liable for inaccuracies in AI-generated copy.' },
            { title: '6. Intellectual Property', body: 'You own all content you generate using ListOps. We retain ownership of the platform, AI prompts, and infrastructure. You grant us a limited license to process your data to provide the service.' },
            { title: '7. Limitation of Liability', body: 'ListOps\'s liability is limited to the amount you paid in the 3 months preceding any claim. We are not liable for indirect, consequential, or punitive damages.' },
            { title: '8. Governing Law', body: 'These terms are governed by the laws of the State of Texas, United States. Disputes shall be resolved in the courts of Travis County, Texas.' },
          ].map((section) => (
            <div key={section.title}>
              <h2 className="font-display text-lg font-semibold text-slate-900 mb-2">{section.title}</h2>
              <p>{section.body}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
